export const DESTINATIONS = {
  Europe: {
    "Top Countries": [
      "France",
      "Germany",
      "Italy",
      "Spain",
      "United Kingdom",
      "Netherlands",
      "Switzerland",
      "Greece",
      "Austria",
      "Portugal",
    ],
    "Top Cities": [
      "Paris",
      "Berlin",
      "Rome",
      "Barcelona",
      "London",
      "Amsterdam",
      "Zurich",
      "Athens",
      "Vienna",
      "Lisbon",
    ],
    "Top Locations": [
      "Eiffel Tower",
      "Brandenburg Gate",
      "Colosseum",
      "Sagrada Familia",
      "Big Ben",
      "Rijksmuseum",
      "Lake Geneva",
      "Acropolis",
      "Schonbrunn Palace",
      "Belem Tower",
    ],
  },
  Asia: {
    "Top Countries": [
      "China",
      "Japan",
      "India",
      "South Korea",
      "Thailand",
      "Vietnam",
      "Malaysia",
      "Indonesia",
      "Singapore",
      "United Arab Emirates",
    ],
    "Top Cities": [
      "Beijing",
      "Tokyo",
      "Mumbai",
      "Seoul",
      "Bangkok",
      "Hanoi",
      "Kuala Lumpur",
      "Jakarta",
      "Singapore",
      "Dubai",
    ],
    "Top Locations": [
      "Great Wall of China",
      "Mount Fuji",
      "Taj Mahal",
      "Gyeongbokgung Palace",
      "Grand Palace",
      "Ha Long Bay",
      "Petronas Towers",
      "Borobudur",
      "Marina Bay Sands",
      "Burj Khalifa",
    ],
  },
  NorthAmerica: {
    "Top Countries": [
      "United States",
      "Canada",
      "Mexico",
      "Cuba",
      "Jamaica",
      "Dominican Republic",
      "Costa Rica",
      "Panama",
      "Guatemala",
      "Honduras",
    ],
    "Top Cities": [
      "New York",
      "Toronto",
      "Mexico City",
      "Havana",
      "Kingston",
      "Punta Cana",
      "San Jose",
      "Panama City",
      "Guatemala City",
      "Tegucigalpa",
    ],
    "Top Locations": [
      "Statue of Liberty",
      "CN Tower",
      "Chichen Itza",
      "Malecon",
      "Dunn's River Falls",
      "Bavaro Beach",
      "Arenal Volcano",
      "Panama Canal",
      "Tikal",
      "Copan Ruins",
    ],
  },
  SouthAmerica: {
    "Top Countries": [
      "Brazil",
      "Argentina",
      "Chile",
      "Peru",
      "Colombia",
      "Uruguay",
      "Bolivia",
      "Paraguay",
      "Ecuador",
      "Venezuela",
    ],
    "Top Cities": [
      "Rio de Janeiro",
      "Buenos Aires",
      "Santiago",
      "Lima",
      "Bogota",
      "Montevideo",
      "La Paz",
      "Asuncion",
      "Quito",
      "Caracas",
    ],
    "Top Locations": [
      "Christ the Redeemer",
      "Iguazu Falls",
      "Torres del Paine",
      "Machu Picchu",
      "Cartagena Old Town",
      "Punta del Este",
      "Salar de Uyuni",
      "Itaipu Dam",
      "Galapagos Islands",
      "Angel Falls",
    ],
  },
  Africa: {
    "Top Countries": [
      "South Africa",
      "Egypt",
      "Morocco",
      "Kenya",
      "Tanzania",
      "Nigeria",
      "Ghana",
      "Ethiopia",
      "Uganda",
      "Namibia",
    ],
    "Top Cities": [
      "Cape Town",
      "Cairo",
      "Marrakech",
      "Nairobi",
      "Dar es Salaam",
      "Lagos",
      "Accra",
      "Addis Ababa",
      "Kampala",
      "Windhoek",
    ],
    "Top Locations": [
      "Table Mountain",
      "Pyramids of Giza",
      "Jemaa el-Fnaa",
      "Maasai Mara",
      "Serengeti",
      "Lekki Conservation Centre",
      "Cape Coast Castle",
      "Lalibela",
      "Bwindi Impenetrable Forest",
      "Sossusvlei",
    ],
  },
  Oceania: {
    "Top Countries": [
      "Australia",
      "New Zealand",
      "Fiji",
      "Papua New Guinea",
      "Samoa",
      "Tonga",
      "Vanuatu",
      "Solomon Islands",
      "Micronesia",
      "Palau",
    ],
    "Top Cities": [
      "Sydney",
      "Auckland",
      "Suva",
      "Port Moresby",
      "Apia",
      "Nuku'alofa",
      "Port Vila",
      "Honiara",
      "Palikir",
      "Ngerulmud",
    ],
    "Top Locations": [
      "Sydney Opera House",
      "Milford Sound",
      "Coral Coast",
      "Kokoda Track",
      "To-Sua Ocean Trench",
      "Ha'atafu Beach",
      "Mount Yasur",
      "Mataniko Falls",
      "Nan Madol",
      "Rock Islands",
    ],
  },
  Polar: {
    "Top Countries": [
      "Antarctica",
      "Greenland",
      "Iceland",
      "Norway",
      "Finland",
      "Sweden",
      "Russia",
      "Canada",
      "United States",
      "Argentina",
    ],
    "Top Cities": [
      "McMurdo Station",
      "Nuuk",
      "Reykjavik",
      "Tromso",
      "Rovaniemi",
      "Kiruna",
      "Murmansk",
      "Iqaluit",
      "Barrow",
      "Ushuaia",
    ],
    "Top Locations": [
      "South Pole",
      "Ilulissat Icefjord",
      "Blue Lagoon",
      "Northern Lights",
      "Santa Claus Village",
      "Icehotel",
      "Lake Baikal",
      "Banff National Park",
      "Denali National Park",
      "Tierra del Fuego",
    ],
  },
};

export const ACTIVITIES = {
  "Top world landmarks": {
    "Highly Rated": [
      "Eiffel Tower, France",
      "Colosseum, Italy",
      "Big Ben, United Kingdom",
      "Sagrada Familia, Spain",
      "Acropolis, Greece",
      "Brandenburg Gate, Germany",
      "Rijksmuseum, Netherlands",
      "Schonbrunn Palace, Austria",
      "Belem Tower, Portugal",
      "Lake Geneva, Switzerland",
    ],
    "On Demand": [
      "Buckingham Palace, United Kingdom",
      "Neuschwanstein Castle, Germany",
      "Trevi Fountain, Italy",
      "La Rambla, Spain",
      "Notre Dame, France",
      "Vatican City, Italy",
      "Anne Frank House, Netherlands",
      "Belvedere Palace, Austria",
      "Monastery of Jeronimos, Portugal",
      "Chillon Castle, Switzerland",
    ],
  },
  "Food and Nightlife": {
    "Highly Rated": [
      "Paris, France",
      "Barcelona, Spain",
      "Berlin, Germany",
      "Rome, Italy",
      "Amsterdam, Netherlands",
      "Athens, Greece",
      "Vienna, Austria",
      "Lisbon, Portugal",
      "Zurich, Switzerland",
      "London, United Kingdom",
    ],
    "On Demand": [
      "Madrid, Spain",
      "Milan, Italy",
      "Prague, Czech Republic",
      "Munich, Germany",
      "Brussels, Belgium",
      "Budapest, Hungary",
      "Copenhagen, Denmark",
      "Dublin, Ireland",
      "Stockholm, Sweden",
      "Warsaw, Poland",
    ],
  },
  "Adventure and Sport": {
    "Highly Rated": [
      "Swiss Alps, Switzerland",
      "Pyrenees, Spain/France",
      "Dolomites, Italy",
      "Lake District, United Kingdom",
      "Black Forest, Germany",
      "Tatra Mountains, Poland/Slovakia",
      "Julian Alps, Slovenia",
      "Mont Blanc, France",
      "High Tatras, Slovakia",
      "Algarve, Portugal",
    ],
    "On Demand": [
      "Scottish Highlands, United Kingdom",
      "Vosges, France",
      "Carpathians, Romania",
      "Olympus, Greece",
      "Sierra Nevada, Spain",
      "Abruzzo, Italy",
      "Bavarian Alps, Germany",
      "Cantabrian Mountains, Spain",
      "Rila, Bulgaria",
      "Mount Etna, Italy",
    ],
  },
  "Landscapes and Nature": {
    "Highly Rated": [
      "Plitvice Lakes, Croatia",
      "Cliffs of Moher, Ireland",
      "Lake Bled, Slovenia",
      "Geirangerfjord, Norway",
      "Faroe Islands, Denmark",
      "Santorini, Greece",
      "Madeira, Portugal",
      "Lake District, United Kingdom",
      "Scottish Highlands, United Kingdom",
      "Iceland",
    ],
    "On Demand": [
      "Dolomites, Italy",
      "Cinque Terre, Italy",
      "Loire Valley, France",
      "Saxon Switzerland, Germany",
      "Hallstatt, Austria",
      "Isle of Skye, Scotland",
      "Grossglockner, Austria",
      "Hohenzollern Castle, Germany",
      "Mount Pilatus, Switzerland",
      "Blue Lagoon, Iceland",
    ],
  },
  "Boat Tours": {
    "Highly Rated": [
      "Amsterdam Canals, Netherlands",
      "Venice, Italy",
      "Rhine River, Germany",
      "Danube River, Hungary/Austria",
      "Greek Islands, Greece",
      "Norwegian Fjords, Norway",
      "Thames River, United Kingdom",
      "Seine River, France",
      "Dalmatian Coast, Croatia",
      "Baltic Sea, Northern Europe",
    ],
    "On Demand": [
      "Loire River, France",
      "Lake Geneva, Switzerland",
      "Shannon River, Ireland",
      "Göta Canal, Sweden",
      "Douro River, Portugal",
      "Tiber River, Italy",
      "Lake Bled, Slovenia",
      "Main River, Germany",
      "Sava River, Balkans",
      "Clyde River, Scotland",
    ],
  },
  "Water Sport": {
    "Highly Rated": [
      "Mediterranean Sea, Southern Europe",
      "Greek Islands, Greece",
      "Amalfi Coast, Italy",
      "Costa Brava, Spain",
      "French Riviera, France",
      "Dalmatian Coast, Croatia",
      "Cornwall, United Kingdom",
      "Algarve, Portugal",
      "Lake Geneva, Switzerland",
      "Iceland",
    ],
    "On Demand": [
      "Sardinia, Italy",
      "Mykonos, Greece",
      "Mallorca, Spain",
      "Corsica, France",
      "Cote d'Azur, France",
      "Ibiza, Spain",
      "Sicily, Italy",
      "Madeira, Portugal",
      "Lake Balaton, Hungary",
      "Black Sea Coast, Bulgaria",
    ],
  },
  "Air Tours": {
    "Highly Rated": [
      "Swiss Alps, Switzerland",
      "Mont Blanc, France",
      "Scottish Highlands, United Kingdom",
      "Lake Bled, Slovenia",
      "Norwegian Fjords, Norway",
      "Santorini, Greece",
      "Iceland",
      "Dolomites, Italy",
      "Pyrenees, Spain/France",
      "Bavarian Alps, Germany",
    ],
    "On Demand": [
      "Blue Lagoon, Iceland",
      "Faroe Islands, Denmark",
      "Black Forest, Germany",
      "Tatra Mountains, Poland/Slovakia",
      "Vosges, France",
      "Julian Alps, Slovenia",
      "Abruzzo, Italy",
      "Olympus, Greece",
      "Sierra Nevada, Spain",
      "Cantabrian Mountains, Spain",
    ],
  },
  "Road Trips": {
    "Highly Rated": [
      "Ring of Kerry, Ireland",
      "Amalfi Coast, Italy",
      "Route One, Iceland",
      "Great Dolomites Road, Italy",
      "Grossglockner High Alpine Road, Austria",
      "Romantic Road, Germany",
      "North Coast 500, Scotland",
      "Black Forest High Road, Germany",
      "Transfagarasan, Romania",
      "Causeway Coastal Route, Northern Ireland",
    ],
    "On Demand": [
      "Basque Circuit, Spain",
      "Atlantic Road, Norway",
      "Route Napoleon, France",
      "Algarve, Portugal",
      "Trollstigen, Norway",
      "Wild Atlantic Way, Ireland",
      "Cornwall, United Kingdom",
      "Saxon Switzerland, Germany",
      "Great Alpine Road, France",
      "Haute Route, Switzerland/France",
    ],
  },
};

export const CURRENCIES = [
  {label: "U.S. Dollar", value: "USD"},
  // {label: "U.A. Dinar", value: "UAE"},
];

export const SEARCH_SUGGESTIONS = [
  {
    destination: "Paris",
    destinationType: "City",
    destinationId: "a2b410d3",
  },
  {
    destination: "Bangkok",
    destinationType: "City",
    destinationId: "10b2afa4",
  },
  {
    destination: "Florida",
    destinationType: "State",
    destinationId: "5b59e3e9",
  },
  {
    destination: "Tamil Nadu",
    destinationType: "State",
    destinationId: "1525c1e2",
  },
  {
    destination: "France",
    destinationType: "Country",
    destinationId: "3083e030",
  },
];
