export const DESTINATIONS = {
  Europe: {
    "Top Countries": [
      {name: "France", url: "/tours/France/3083e030"},
      {name: "Germany", url: "/tours/Germany/8776e078"},
      {name: "Italy", url: "/tours/Italy/24ed5a83"},
      {name: "Spain", url: "/tours/Spain/5b352a10"},
      {name: "United Kingdom", url: "/tours/United-Kingdom/ede98683"},
      {name: "Netherlands", url: "/tours/Netherlands/8d19c558"},
      {name: "Switzerland", url: "/tours/Switzerland/7f094d77"},
      {name: "Greece", url: "/tours/Greece/037794d3"},
      {name: "Austria", url: "/tours/Austria/5d8974a6"},
      {name: "Portugal", url: "/tours/Portugal/1ae66b55"},
    ],
    "Top Cities": [
      {name: "Paris", url: "/tours/Paris/a2b410d3"},
      {name: "Berlin", url: "/tours/Berlin/725bcbe4"},
      {name: "Rome", url: "/tours/Rome/4897ca95"},
      {name: "Barcelona", url: "/tours/Barcelona/f0b8b11e"},
      {name: "London", url: "/tours/London/9d8dd2d1"},
      {name: "Amsterdam", url: "/tours/Amsterdam/962c662a"},
      {name: "Zurich", url: "/tours/Zurich/9f746cc8"},
      {name: "Athens", url: "/tours/Athens/84b4ef16"},
      {name: "Vienna", url: "/tours/Vienna/a685430f"},
      {name: "Lisbon", url: "/tours/Lisbon/91a05467"},
    ],
  },
  Asia: {
    "Top Countries": [
      {name: "China", url: "/tours/China/dc32f39f"},
      {name: "Japan", url: "/tours/Japan/7eb9f6ce"},
      {name: "India", url: "/tours/India/f07cf0fc"},
      {name: "South Korea", url: "/tours/South-Korea/7206b2b5"},
      {name: "Thailand", url: "/tours/Thailand/27e024cd"},
      {name: "Vietnam", url: "/tours/Vietnam/de20819b"},
      {name: "Malaysia", url: "/tours/Malaysia/610e1151"},
      {name: "Indonesia", url: "/tours/Indonesia/eda1239d"},
      {name: "Singapore", url: "/tours/Singapore/86f2c564"},
      {name: "United Arab Emirates", url: "/tours/United-Arab-Emirates"},
    ],
    "Top Cities": [
      {name: "Beijing", url: "/tours/Beijing/461e1b35"},
      {name: "Tokyo", url: "/tours/Tokyo/813331c1"},
      {name: "Mumbai", url: "/tours/Mumbai/2a5d4329"},
      {name: "Seoul", url: "/tours/Seoul/72efac79"},
      {name: "Bangkok", url: "/tours/Bangkok/10b2afa4"},
      {name: "Hanoi", url: "/tours/Hanoi/f0b556c3"},
      {name: "Kuala Lumpur", url: "/tours/Kuala-Lumpur/790ae472"},
      {name: "Jakarta", url: "/tours/Jakarta/68853ba6"},
      {name: "Singapore", url: "/tours/Singapore/7e0f19c9"},
      {name: "Dubai", url: "/tours/Dubai/55754ef6"},
    ],
  },
  NorthAmerica: {
    "Top Countries": [
      {name: "United States", url: "/tours/United-States/edbdc2ef"},
      {name: "Canada", url: "/tours/Canada/fea9d636"},
      {name: "Mexico", url: "/tours/Mexico/a829ee2d"},
      {name: "Cuba", url: "/tours/Cuba/cc5599e4"},
      {name: "Jamaica", url: "/tours/Jamaica/a905070b"},
      {name: "Dominican Republic", url: "/tours/Dominican-Republic/296e3d0e"},
      {name: "Costa Rica", url: "/tours/Costa-Rica/938e45b6"},
      {name: "Panama", url: "/tours/Panama/f458e814"},
      {name: "Guatemala", url: "/tours/Guatemala/8acafee7"},
      {name: "Honduras", url: "/tours/Honduras/ea102e69"},
    ],
    "Top Cities": [
      {name: "New York", url: "/tours/New-York/b00378e0"},
      {name: "Toronto", url: "/tours/Toronto/853476cc"},
      {name: "Mexico City", url: "/tours/Mexico-City/69ee522d"},
      {name: "Havana", url: "/tours/Havana/976e1e25"},
      {name: "Kingston", url: "/tours/Kingston/8d79f3bb"},
      {name: "Punta Cana", url: "/tours/Punta-Cana/679f4cd0"},
      {name: "San Jose", url: "/tours/San-Jose/f97e2795"},
      {name: "Panama City", url: "/tours/Panama-City/039eb01f"},
      {name: "Guatemala City", url: "/tours/Guatemala-City/81051241"},
      {name: "Tegucigalpa", url: "/tours/Tegucigalpa/8624b690"},
    ],
  },
  SouthAmerica: {
    "Top Countries": [
      {name: "Brazil", url: "/tours/Brazil/3251bfc2"},
      {name: "Argentina", url: "/tours/Argentina/23592a71"},
      {name: "Chile", url: "/tours/Chile/2d97d248"},
      {name: "Peru", url: "/tours/Peru/2d493f95"},
      {name: "Colombia", url: "/tours/Colombia/63202250"},
      {name: "Uruguay", url: "/tours/Uruguay/f73e69ff"},
      {name: "Bolivia", url: "/tours/Bolivia/3d04fe50"},
      {name: "Paraguay", url: "/tours/Paraguay/dd537d89"},
      {name: "Ecuador", url: "/tours/Ecuador/81a4def2"},
      {name: "Venezuela", url: "/tours/Venezuela/8adc909a"},
    ],
    "Top Cities": [
      {name: "Rio de Janeiro", url: "/tours/Rio-de-Janeiro/92d194eb"},
      {name: "Buenos Aires", url: "/tours/Buenos-Aires/aecb212f"},
      {name: "Santiago", url: "/tours/Santiago/a5bd1ac2"},
      {name: "Lima", url: "/tours/Lima/1056c941"},
      {name: "Bogota", url: "/tours/Bogota/f2389e90"},
      {name: "Montevideo", url: "/tours/Montevideo/c869992e"},
      {name: "La Paz", url: "/tours/La-Paz/6b4d4c84"},
      {name: "Asuncion", url: "/tours/Asuncion/5384fc3a"},
      {name: "Quito", url: "/tours/Quito/b9ceda10"},
      {name: "Caracas", url: "/tours/Caracas/8e630003"},
    ],
  },
  Africa: {
    "Top Countries": [
      {name: "South Africa", url: "/tours/South-Africa/724453ab"},
      {name: "Egypt", url: "/tours/Egypt/99d83f13"},
      {name: "Morocco", url: "/tours/Morocco/e672d6a9"},
      {name: "Kenya", url: "/tours/Kenya/fe196593"},
      {name: "Tanzania", url: "/tours/Tanzania/ffe0e553"},
      {name: "Nigeria", url: "/tours/Nigeria/94b00949"},
      {name: "Ghana", url: "/tours/Ghana/cd65881e"},
      {name: "Ethiopia", url: "/tours/Ethiopia/66b020f0"},
      {name: "Uganda", url: "/tours/Uganda/577df463"},
      {name: "Namibia", url: "/tours/Namibia/07bdda16"},
    ],
    "Top Cities": [
      {name: "Cape Town", url: "/tours/Cape-Town/1fa891f9"},
      {name: "Cairo", url: "/tours/Cairo/aac72b0b"},
      {name: "Marrakech", url: "/tours/Marrakech/2703cdb0"},
      {name: "Nairobi", url: "/tours/Nairobi/94696e72"},
      {name: "Dar es Salaam", url: "/tours/Dar-es-Salaam/21b1bc16"},
      {name: "Lagos", url: "/tours/Lagos/3ba15cf4"},
      {name: "Accra", url: "/tours/Accra/603b7389"},
      {name: "Addis Ababa", url: "/tours/Addis-Ababa/c7cb0fe4"},
      {name: "Kampala", url: "/tours/Kampala/d77ed5bb"},
      {name: "Windhoek", url: "/tours/Windhoek/5caa5d63"},
    ],
  },
  Oceania: {
    "Top Countries": [
      {name: "Australia", url: "/tours/Australia/dacf7c88"},
      {name: "New Zealand", url: "/tours/New-Zealand/49703eb4"},
      {name: "Fiji", url: "/tours/Fiji/720b6a5d"},
      {name: "Papua New Guinea", url: "/tours/Papua-New-Guinea/9342a02a"},
      {name: "Samoa", url: "/tours/Samoa/56d988ff"},
      {name: "Tonga", url: "/tours/Tonga/8d91b2f6"},
      {name: "Vanuatu", url: "/tours/Vanuatu/a3f94342"},
      {name: "Solomon Islands", url: "/tours/Solomon-Islands/2b0dbd49"},
      {name: "Micronesia", url: "/tours/Micronesia/da5a47c0"},
      {name: "Palau", url: "/tours/Palau/73b7a795"},
    ],
    "Top Cities": [
      {name: "Sydney", url: "/tours/Sydney/906c0461"},
      {name: "Auckland", url: "/tours/Auckland/b90634da"},
      {name: "Suva", url: "/tours/Suva/eb2d6ed6"},
      {name: "Port Moresby", url: "/tours/Port-Moresby/9a8c9f7c"},
      {name: "Apia", url: "/tours/Apia/e616fb49"},
      {name: "Nuku'alofa", url: "/tours/Nuku'alofa/15408e4b"},
      {name: "Port Vila", url: "/tours/Port-Vila/1d83e6d9"},
      {name: "Honiara", url: "/tours/Honiara/144f6286"},
      {name: "Palikir", url: "/tours/Palikir/90994ae1"},
      {name: "Ngerulmud", url: "/tours/Ngerulmud/e644b1c1"},
    ],
  },
  Polar: {
    "Top Countries": [
      {name: "Antarctica", url: "/tours/Antarctica/41cfd7d0"},
      {name: "Greenland", url: "/tours/Greenland/93645e0a"},
      {name: "Iceland", url: "/tours/Iceland/f9bf5eb2"},
      {name: "Norway", url: "/tours/Norway/b961a3aa"},
      {name: "Finland", url: "/tours/Finland/907939f6"},
      {name: "Sweden", url: "/tours/Sweden/10c92f72"},
      {name: "Russia", url: "/tours/Russia/2ad20906"},
      {name: "Canada", url: "/tours/Canada/fea9d636"},
      {name: "United States", url: "/tours/United-States/3f8b8295"},
      {name: "Argentina", url: "/tours/Argentina/23592a71"},
    ],
    "Top Cities": [
      {name: "McMurdo Station", url: "/tours/McMurdo-Station/d8699107"},
      {name: "Nuuk", url: "/tours/Nuuk/2f1f7be0"},
      {name: "Reykjavik", url: "/tours/Reykjavik/e2737b7c"},
      {name: "Tromso", url: "/tours/Tromso/857b19d8"},
      {name: "Rovaniemi", url: "/tours/Rovaniemi/bcf2b793"},
      {name: "Kiruna", url: "/tours/Kiruna/4a4ce948"},
      {name: "Murmansk", url: "/tours/Murmansk/703471a5"},
      {name: "Iqaluit", url: "/tours/Iqaluit/39f5da6f"},
      {name: "Barrow", url: "/tours/Barrow/a845ba43"},
      {name: "Ushuaia", url: "/tours/Ushuaia/9d861835"},
    ],
  },
};

export const ACTIVITIES = {
  "Top world landmarks": {
    "Highly Rated": [
      {name: "Eiffel Tower", url: "/tours/eiffel-tower"},
      {name: "Colosseum", url: "/tours/colosseum"},
      {name: "Big Ben", url: "/tours/big-ben"},
      {name: "Sagrada Familia", url: "/tours/sagrada-familia"},
      {name: "Acropolis", url: "/tours/acropolis"},
      {name: "Brandenburg Gate", url: "/tours/brandenburg-gate"},
      {
        name: "Rijksmuseum",
        url: "/tours/rijksmuseum",
      },
      {
        name: "Schonbrunn Palace",
        url: "/tours/schonbrunn-palace",
      },
      {
        name: "Belem Tower",
        url: "/tours/belem-tower",
      },
      {
        name: "Lake Geneva",
        url: "/tours/lake-geneva",
      },
    ],
    "On Demand": [
      {
        name: "Buckingham Palace",
        url: "/tours/buckingham-palace",
      },
      {
        name: "Neuschwanstein Castle",
        url: "/tours/neuschwanstein-castle",
      },
      {
        name: "Trevi Fountain",
        url: "/tours/trevi-fountain",
      },
      {name: "La Rambla", url: "/tours/la-rambla"},
      {
        name: "Notre Dame",
        url: "/tours/notre-dame",
      },
      {name: "Vatican City", url: "/tours/vatican-city"},
      {name: "Anne Frank House", url: "/tours/anne-frank-house"},
      {name: "Belvedere Palace", url: "/tours/belvedere-palace"},

      {
        name: "Monastery of Jeronimos",
        url: "/tours/monastery-of-jeronimos",
      },
      {name: "Chillon Castle", url: "/tours/chillon-castle"},
    ],
  },
  "Food and Nightlife": {
    "Highly Rated": [
      {name: "Paris", url: "/tours/paris"},
      {name: "Barcelona", url: "/tours/barcelona"},
      {name: "Berlin", url: "/tours/berlin"},
      {name: "Rome", url: "/tours/rome"},
      {name: "Amsterdam", url: "/tours/amsterdam"},
      {name: "Athens", url: "/tours/athens"},
      {name: "Vienna", url: "/tours/vienna"},
      {name: "Lisbon", url: "/tours/lisbon"},
      {name: "Zurich", url: "/tours/zurich"},
      {name: "London", url: "/tours/london"},
    ],
    "On Demand": [
      {name: "Madrid", url: "/tours/madrid"},
      {name: "Milan", url: "/tours/milan"},
      {name: "Prague", url: "/tours/prague"},
      {name: "Munich", url: "/tours/munich"},
      {name: "Brussels", url: "/tours/brussels"},
      {name: "Budapest", url: "/tours/budapest"},
      {name: "Copenhagen", url: "/tours/copenhagen"},
      {name: "Dublin", url: "/tours/dublin"},
      {name: "Stockholm", url: "/tours/stockholm"},
      {name: "Warsaw", url: "/tours/warsaw"},
    ],
  },
  "Adventure and Sport": {
    "Highly Rated": [
      {name: "Swiss Alps", url: "/tours/swiss-alps"},
      {name: "Pyrenees", url: "/tours/pyrenees"},
      {name: "Dolomites", url: "/tours/dolomites"},
      {name: "Lake District", url: "/tours/lake-district"},
      {name: "Black Forest", url: "/tours/black-forest"},
      {name: "Tatra Mountains", url: "/tours/tatra-mountains"},
      {name: "Julian Alps", url: "/tours/julian-alps"},
      {name: "Mont Blanc", url: "/tours/mont-blanc"},
      {name: "High Tatras", url: "/tours/high-tatras"},
      {name: "Algarve", url: "/tours/algarve"},
    ],
    "On Demand": [
      {name: "Scottish Highlands", url: "/tours/scottish-highlands"},
      {name: "Vosges", url: "/tours/vosges"},
      {name: "Carpathians", url: "/tours/carpathians"},
      {name: "Olympus", url: "/tours/olympus"},
      {name: "Sierra Nevada", url: "/tours/sierra-nevada"},
      {name: "Abruzzo", url: "/tours/abruzzo"},
      {name: "Bavarian Alps", url: "/tours/bavarian-alps"},
      {name: "Cantabrian Mountains", url: "/tours/cantabrian-mountains"},
      {name: "Rila", url: "/tours/rila"},
      {name: "Mount Etna", url: "/tours/mount-etna"},
    ],
  },
  "Landscapes and Nature": {
    "Highly Rated": [
      {name: "Plitvice Lakes", url: "/tours/plitvice-lakes"},
      {name: "Cliffs of Moher", url: "/tours/cliffs-of-moher"},
      {name: "Lake Bled", url: "/tours/lake-bled"},
      {name: "Geirangerfjord", url: "/tours/geirangerfjord"},
      {name: "Faroe Islands", url: "/tours/faroe-islands"},
      {name: "Santorini", url: "/tours/santorini"},
      {name: "Madeira", url: "/tours/madeira"},
      {name: "Lake District", url: "/tours/lake-district"},
      {name: "Scottish Highlands", url: "/tours/scottish-highlands"},
      {name: "Iceland", url: "/tours/iceland"},
    ],
    "On Demand": [
      {name: "Dolomites", url: "/tours/dolomites"},
      {name: "Cinque Terre", url: "/tours/cinque-terre"},
      {name: "Loire Valley", url: "/tours/loire-valley"},
      {name: "Saxon Switzerland", url: "/tours/saxon-switzerland"},
      {name: "Hallstatt", url: "/tours/hallstatt"},
      {name: "Isle of Skye", url: "/tours/isle-of-skye"},
      {name: "Grossglockner", url: "/tours/grossglockner"},
      {name: "Hohenzollern Castle", url: "/tours/hohenzollern-castle"},
      {name: "Mount Pilatus", url: "/tours/mount-pilatus"},
      {name: "Blue Lagoon", url: "/tours/blue-lagoon"},
    ],
  },
  "Boat Tours": {
    "Highly Rated": [
      {name: "Amsterdam Canals", url: "/tours/amsterdam-canals"},
      {name: "Venice", url: "/tours/venice"},
      {name: "Rhine River", url: "/tours/rhine-river"},
      {name: "Danube River", url: "/tours/danube-river"},
      {name: "Greek Islands", url: "/tours/greek-islands"},
      {name: "Norwegian Fjords", url: "/tours/norwegian-fjords"},
      {name: "Thames River", url: "/tours/thames-river"},
      {name: "Seine River", url: "/tours/seine-river"},
      {name: "Dalmatian Coast", url: "/tours/dalmatian-coast"},
      {name: "Baltic Sea", url: "/tours/baltic-sea"},
    ],
    "On Demand": [
      {name: "Loire River", url: "/tours/loire-river"},
      {name: "Lake Geneva", url: "/tours/lake-geneva"},
      {name: "Shannon River", url: "/tours/shannon-river"},
      {name: "Göta Canal", url: "/tours/gota-canal"},
      {name: "Douro River", url: "/tours/douro-river"},
      {name: "Tiber River", url: "/tours/tiber-river"},
      {name: "Lake Bled", url: "/tours/lake-bled"},
      {name: "Main River", url: "/tours/main-river"},
      {name: "Sava River", url: "/tours/sava-river"},
      {name: "Clyde River", url: "/tours/clyde-river"},
    ],
  },
  "Water Sport": {
    "Highly Rated": [
      {name: "Mediterranean Sea", url: "/tours/mediterranean-sea"},
      {name: "Greek Islands", url: "/tours/greek-islands"},
      {name: "Amalfi Coast", url: "/tours/amalfi-coast"},
      {name: "Costa Brava", url: "/tours/costa-brava"},
      {name: "French Riviera", url: "/tours/french-riviera"},
      {name: "Dalmatian Coast", url: "/tours/dalmatian-coast"},
      {name: "Cornwall", url: "/tours/cornwall"},
      {name: "Algarve", url: "/tours/algarve"},
      {name: "Lake Geneva", url: "/tours/lake-geneva"},
      {name: "Iceland", url: "/tours/iceland"},
    ],
    "On Demand": [
      {name: "Sardinia", url: "/tours/sardinia"},
      {name: "Mykonos", url: "/tours/mykonos"},
      {name: "Mallorca", url: "/tours/mallorca"},
      {name: "Corsica", url: "/tours/corsica"},
      {name: "Cote d'Azur", url: "/tours/cote-dazur"},
      {name: "Ibiza", url: "/tours/ibiza"},
      {name: "Sicily", url: "/tours/sicily"},
      {name: "Madeira", url: "/tours/madeira"},
      {name: "Lake Balaton", url: "/tours/lake-balaton"},
      {name: "Black Sea Coast", url: "/tours/black-sea-coast"},
    ],
  },
  "Air Tours": {
    "Highly Rated": [
      {name: "Swiss Alps", url: "/tours/swiss-alps"},
      {name: "Mont Blanc", url: "/tours/mont-blanc"},
      {name: "Scottish Highlands", url: "/tours/scottish-highlands"},
      {name: "Lake Bled", url: "/tours/lake-bled"},
      {name: "Norwegian Fjords", url: "/tours/norwegian-fjords"},
      {name: "Santorini", url: "/tours/santorini"},
      {name: "Iceland", url: "/tours/iceland"},
      {name: "Dolomites", url: "/tours/dolomites"},
      {name: "Pyrenees", url: "/tours/pyrenees"},
      {name: "Bavarian Alps", url: "/tours/bavarian-alps"},
    ],
    "On Demand": [
      {name: "Blue Lagoon", url: "/tours/blue-lagoon"},
      {name: "Faroe Islands", url: "/tours/faroe-islands"},
      {name: "Black Forest", url: "/tours/black-forest"},
      {name: "Tatra Mountains", url: "/tours/tatra-mountains"},
      {name: "Vosges", url: "/tours/vosges"},
      {name: "Julian Alps", url: "/tours/julian-alps"},
      {name: "Abruzzo", url: "/tours/abruzzo"},
      {name: "Olympus", url: "/tours/olympus"},
      {name: "Sierra Nevada", url: "/tours/sierra-nevada"},
      {name: "Cantabrian Mountains", url: "/tours/cantabrian-mountains"},
    ],
  },
  "Road Trips": {
    "Highly Rated": [
      {name: "Ring of Kerry", url: "/tours/ring-of-kerry"},
      {name: "Amalfi Coast", url: "/tours/amalfi-coast"},
      {name: "Route One", url: "/tours/route-one"},
      {name: "Great Dolomites Road", url: "/tours/great-dolomites-road"},
      {
        name: "Grossglockner High Alpine Road",
        url: "/tours/grossglockner",
      },
      {name: "Romantic Road", url: "/tours/romantic-road"},
      {name: "North Coast 500", url: "/tours/north-coast-500"},
      {name: "Black Forest High Road", url: "/tours/black-forest"},
      {name: "Transfagarasan", url: "/tours/transfagarasan"},
      {
        name: "Causeway Coastal Route",
        url: "/tours/causeway-coastal-route",
      },
    ],
    "On Demand": [
      {name: "Basque Circuit", url: "/tours/basque-circuit"},
      {name: "Atlantic Road", url: "/tours/atlantic-road"},
      {name: "Route Napoleon", url: "/tours/route-napoleon"},
      {name: "Algarve", url: "/tours/algarve"},
      {name: "Trollstigen", url: "/tours/trollstigen"},
      {name: "Wild Atlantic Way", url: "/tours/wild-atlantic-way"},
      {name: "Cornwall", url: "/tours/cornwall"},
      {name: "Saxon Switzerland", url: "/tours/saxon-switzerland"},
      {name: "Great Alpine Road", url: "/tours/great-alpine-road"},
      {name: "Haute Route", url: "/tours/haute-route"},
    ],
  },
};

export const CURRENCIES = [{label: "U.S. Dollar", value: "USD"}];

export const SEARCH_SUGGESTIONS = [
  {
    destination: "Paris",
    destinationType: "City",
    destinationId: "a2b410d3",
  },
  {
    destination: "Bangkok",
    destinationType: "City",
    destinationId: "10b2afa4",
  },
  {
    destination: "Florida",
    destinationType: "State",
    destinationId: "5b59e3e9",
  },
  {
    destination: "Tamil Nadu",
    destinationType: "State",
    destinationId: "1525c1e2",
  },
  {
    destination: "France",
    destinationType: "Country",
    destinationId: "3083e030",
  },
];
